// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramBot.DataAccess;

namespace TelegramBot.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220309165702_AddGroupForUsersNew")]
    partial class AddGroupForUsersNew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TelegramBot.Domain.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TelegramBot.Domain.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte>("SubscriptionItem")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("TelegramBot.Domain.Models.TimeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte>("EvenWeek")
                        .HasColumnType("smallint");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("LessonsOfTheDay")
                        .HasColumnType("text");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("TimeTables");
                });

            modelBuilder.Entity("TelegramBot.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<int?>("GroupsId")
                        .HasColumnType("integer");

                    b.Property<long>("IdChat")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GroupsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TelegramBot.Domain.Models.TimeTable", b =>
                {
                    b.HasOne("TelegramBot.Domain.Models.Group", null)
                        .WithMany("TimeTables")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("TelegramBot.Domain.Models.User", b =>
                {
                    b.HasOne("TelegramBot.Domain.Models.Group", "Groups")
                        .WithMany("Users")
                        .HasForeignKey("GroupsId");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("TelegramBot.Domain.Models.Group", b =>
                {
                    b.Navigation("TimeTables");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
